### ISSUE TITLE
Fehler bei der Blocklist-Synchronisation, wenn Nummern mit führenden '+'-Zeichen eingetragen wurden

### ISSUE THREAD

**Issue by haumacher** [haumacher/phoneblock#73]
Aus den Logs:
```
[2024-05-10 17:04:50] ERROR: [de.haumacher.phoneblock.carddav.CardDavServlet]: Failed to process CardDAV request.: java.lang.IllegalArgumentException: Not a digit: +
        at de.haumacher.phoneblock.analysis.NumberTree$Node.index(NumberTree.java:67)
        at de.haumacher.phoneblock.analysis.NumberTree$Node.append(NumberTree.java:44)
        at de.haumacher.phoneblock.analysis.NumberTree$Node.append(NumberTree.java:51)
        at de.haumacher.phoneblock.analysis.NumberTree$Node.append(NumberTree.java:51)
        at de.haumacher.phoneblock.analysis.NumberTree.insert(NumberTree.java:259)
        at de.haumacher.phoneblock.carddav.resource.AddressBookCache.loadNumbers(AddressBookCache.java:189)
        at de.haumacher.phoneblock.carddav.resource.AddressBookCache.loadNumbers(AddressBookCache.java:111)
        at de.haumacher.phoneblock.carddav.resource.AddressBookCache.lookupAddressBook(AddressBookCache.java:90)
        at de.haumacher.phoneblock.carddav.CardDavServlet.getResource(CardDavServlet.java:339)
        at de.haumacher.phoneblock.carddav.CardDavServlet.doPropfind(CardDavServlet.java:169)
        at de.haumacher.phoneblock.carddav.CardDavServlet.service(CardDavServlet.java:89)

```

**Comment by haumacher** [comment]
Es war möglich nach einer Nummer, z.B. `0176506426+02` zu suchen und diese Nummer in die Blockliste eintragen zu lassen. Dabei wurde das ungültige `+`-Zeichen nicht aus der Nummer entfernt. Dieses ungültige Zeichen führte in der Folge zu einem Absturz bei dem Versuch das PhoneBlock-Addressbuch zu erstellen.

**Comment by MarkyMarkDE** [comment]
Wo wir wieder beim Thema sind: traue niemals Nutzereingaben 😉
